config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # redirects old => new
  get "/blog-post/agilitaet-geschwindigkeit/" => redirect("/blog/2018/10/agilitaet-geschwindigkeit")
  get "/blog-post/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat/" => redirect("/blog/2018/10/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat")
  get "/blog-post/teambuilding-mit-market-of-skills/" => redirect("/blog/2018/6/teambuilding-mit-market-of-skills-workshop")
  get "/blog-post/gruendung-mit-hilfe-der-arbeitsagentur/" => redirect("/blog/2018/1/gruendung-mit-hilfe-der-arbeitsagentur")
  get "/blog-post/scrum-3-0-im-einsatz/" => redirect("/blog/2018/1/scrum-30-im-einsatz")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-2/" => redirect("/blog/2017/10/the-next-big-thing-autonomous-self-organized-units-2")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-1/" => redirect("/blog/2017/9/the-next-big-thing-autonomous-self-organized-units-1")

  get "/kontakt", :to => "contact#new", :as => "contact"
  post "/kontakt", :to => "contact#create"

  mount Conferences::API => "/"
  get "/klassenraum", :to => "conferences#classroom"

  authenticate :user do
    resources :profiles, only: [:show, :update] do
      match :change_password, via: [:get, :put]
    end
  end

  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }

  get "/error_test", to: "errors#test", as: "error_test"
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  comfy_route :blog, path: "/blog"
  comfy_route :blog_admin, path: "/blog-admin"
  comfy_route :cms_admin, :path => "/cms"
  comfy_route :cms, path: "/", :sitemap => false

  root to: "cms_content#render_html"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.where(slug: params[:id]).first
  end

  def change_password
    authorize! :update, current_user
    @user = current_user

    if request.put?
      resource_updated = @user.update_with_password(password_update_params)

      if resource_updated
        redirect_to profile_path(@user)
      else
        @user.clean_up_passwords
        respond_with @user
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

  def password_update_params
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/change_password.html.slim
h2.sub_header.menu = title t('devise.passwords.edit.change_my_password')

.left_column
  .sub_list
    = simple_form_for @user, url: profile_change_password_path, html: {method: :put} do |f|
      = f.input :current_password, required: true, autofocus: true
      = f.input :password, input_html: {validate: false}
      = f.input :password_confirmation, required: true
      = f.button :submit, t('devise.passwords.edit.change_my_password'), class: [:btn, :primary]

app/views/profiles/show.html.slim
h1 = title "#{t('fields.hello')} #{@user.first_name}."
.left_column
  .sub_list
    - if @user.avatar.attached?
      = image_tag @user.avatar.variant(resize: "300x300!"), height: '300'
    - else
      = image_pack_tag 'media/images/defaults/user.png', height: '300'

.right_column
  .sub_list
    - if current_user == @user
      p.bold
        = t('activerecord.attributes.user.email')
        |:
        =< @user.email
      p.bold
        = t('activerecord.attributes.user.first_name')
        |:
        =< @user.first_name
      p.bold
        = t('activerecord.attributes.user.surname')
        |:
        =< @user.surname
.clear

- if @user == current_user
  hr
  .box-style.actions
    = link_to t('navigation.signed_out'), destroy_user_session_path, method: :delete, class: [:btn, :secondary], style: 'float:right'
    = link_to t('devise.profile.edit'), edit_user_registration_path(@user), class: [:btn, :secondary]
    = link_to t('devise.passwords.edit.change_my_password'), profile_change_password_path(@user), class: [:btn, :secondary]