config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # redirects old => new
  get "/blog-post/agilitaet-geschwindigkeit/" => redirect("/blog/2018/10/agilitaet-geschwindigkeit")
  get "/blog-post/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat/" => redirect("/blog/2018/10/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat")
  get "/blog-post/teambuilding-mit-market-of-skills/" => redirect("/blog/2018/6/teambuilding-mit-market-of-skills-workshop")
  get "/blog-post/gruendung-mit-hilfe-der-arbeitsagentur/" => redirect("/blog/2018/1/gruendung-mit-hilfe-der-arbeitsagentur")
  get "/blog-post/scrum-3-0-im-einsatz/" => redirect("/blog/2018/1/scrum-30-im-einsatz")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-2/" => redirect("/blog/2017/10/the-next-big-thing-autonomous-self-organized-units-2")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-1/" => redirect("/blog/2017/9/the-next-big-thing-autonomous-self-organized-units-1")

  get "/kontakt", :to => "contact#new", :as => "contact"
  post "/kontakt", :to => "contact#create"

  mount Conferences::API => "/"
  get "/klassenraum", :to => "conferences#classroom"

  authenticate :user do
    resources :profiles, only: [:show, :update] do
      match :change_password, via: [:get, :put]
    end
  end

  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }

  get "/error_test", to: "errors#test", as: "error_test"
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  comfy_route :blog, path: "/blog"
  comfy_route :blog_admin, path: "/blog-admin"
  comfy_route :cms_admin, :path => "/cms"
  comfy_route :cms, path: "/", :sitemap => false

  root to: "cms_content#render_html"
end

app/models/conference.rb
class Conference < ApplicationRecord
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  layout "classroom", only: [:classroom]

  before_action :set_referer, only: [:classroom]
  before_action :authenticate_user!

  def classroom
  end

  private

  def conference_params
    params.require(:conference).permit(:room, :name, :password)
  end

  def set_referer
    session[:referer] = '/klassenraum'
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.slim
= simple_form_for(@conference) do |f|
  = f.error_notification

  .form-inputs
    = f.input :room
    = f.input :name
    = f.input :password

  .form-actions
    = f.button :submit

app/views/conferences/classroom.html.slim
div#meet(style="position: fixed;top: 50px;z-index: 1000;right: 50px;height: 200px;")

iframe(width="100%" style="position: fixed; height: 100%; border: none" src="https://www.youtube.com/embed/tCf-zLRN_XA?autoplay=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen)

= javascript_pack_tag 'conferences'

app/views/conferences/edit.html.slim
h1 Editing conference

== render 'form'

=> link_to 'Show', @conference
'|
=< link_to 'Back', conferences_path

app/views/conferences/index.html.slim
h1 Listing conferences

.left_column
  div#meet

.right_column
  table
    thead
      tr
        th Room
        th Name
        th Password
        th
        th
        th

    tbody
      - @conferences.each do |conference|
        tr
          td = conference.room
          td = conference.name
          td = conference.password
          td = link_to 'Show', conference
          td = link_to 'Edit', edit_conference_path(conference)
          td = link_to 'Destroy', conference, data: { confirm: 'Are you sure?' }, method: :delete

  br

  p= link_to 'New Conference', new_conference_path

  br
  br

  p= link_to "Start Meeting", '#', id: 'js-start-conference'
  p= link_to "Auflegen", '#', id: 'js-stop-conference'
  p= link_to "Toggle Chat", '#', id: 'js-toggle-chat'
  p= link_to "Bildschirm teilen", '#', id: 'js-share-screen'

  br
  br

= javascript_pack_tag 'conferences'

app/views/conferences/new.html.slim
h1 New conference

== render 'form'

= link_to 'Back', conferences_path

app/views/conferences/show.html.slim
p#notice = notice

p
  strong Room:
  = @conference.room
p
  strong Name:
  = @conference.name
p
  strong Password:
  = @conference.password

=> link_to 'Edit', edit_conference_path(@conference)
'|
=< link_to 'Back', conferences_path