config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # redirects old => new
  get "/blog-post/agilitaet-geschwindigkeit/" => redirect("/blog/2018/10/agilitaet-geschwindigkeit")
  get "/blog-post/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat/" => redirect("/blog/2018/10/gedanken-zu-3-gruende-warum-scrum-in-der-politik-nichts-zu-suchen-hat")
  get "/blog-post/teambuilding-mit-market-of-skills/" => redirect("/blog/2018/6/teambuilding-mit-market-of-skills-workshop")
  get "/blog-post/gruendung-mit-hilfe-der-arbeitsagentur/" => redirect("/blog/2018/1/gruendung-mit-hilfe-der-arbeitsagentur")
  get "/blog-post/scrum-3-0-im-einsatz/" => redirect("/blog/2018/1/scrum-30-im-einsatz")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-2/" => redirect("/blog/2017/10/the-next-big-thing-autonomous-self-organized-units-2")
  get "/blog-post/the-next-big-thing-autonomous-self-organized-units-1/" => redirect("/blog/2017/9/the-next-big-thing-autonomous-self-organized-units-1")

  get "/kontakt", :to => "contact#new", :as => "contact"
  post "/kontakt", :to => "contact#create"

  mount Conferences::API => "/"
  get "/klassenraum", :to => "conferences#classroom"

  authenticate :user do
    resources :profiles, only: [:show, :update] do
      match :change_password, via: [:get, :put]
    end
  end

  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions" }

  get "/error_test", to: "errors#test", as: "error_test"
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  comfy_route :blog, path: "/blog"
  comfy_route :blog_admin, path: "/blog-admin"
  comfy_route :cms_admin, :path => "/cms"
  comfy_route :cms, path: "/", :sitemap => false

  root to: "cms_content#render_html"
end

app/views/shared/_admin_navigation.html.slim
- if user_signed_in? and current_user.admin?
  ul.admin_nav.nolist
    li= link_to '/cms', target: '_blank' do
      i.fa.fa-wrench
      =< t('navigation.cms')
    li= link_to '/admin', target: '_blank' do
      i.fa.fa-wrench
      =< t('navigation.admin')
    = yield :admin_menu

app/views/shared/_bottom_navigation.html.slim
- if is_mobile_device?
  - cache ['bottom-nav-mobile', request.path.split('/').second, get_last_updated_at_for(::Comfy::Cms::Page)] do
    = semantic_navigation :primary, builder: Navigasmic::Builder::BottomNavBuilder do |n|
      - n.item "Start", "/", icon: :home
      - ::Comfy::Cms::Page.root.children.published.each do |page|
        - if cms_fragment_content(:nav_item, page) == true
          - main_path = page.full_path.split('/').second
          - n.item page.label, proc{ page.full_path }, icon: cms_fragment_content(:nav_item_icon, page), highlights_on: /^\/#{main_path}/
      - n.item "Blog", "/blog", icon: :blog
      - n.item "Kontakt", "/kontakt", icon: :envelope

app/views/shared/_content_header_margin.html.slim
#content_header_margin
javascript:
    var content_header_margin = getComputedStyle(document.getElementById('header')).height;
    document.getElementById('content_header_margin').style.height = content_header_margin;

app/views/shared/_flash.html.slim
- flash.each do |name, msg|
    = content_tag :div, msg, class: [name, :flash_message], id: "flash_#{name}" if msg.is_a?(String)

app/views/shared/_footer.slim
- cache_if !current_user, ['footer-links-segment', get_last_updated_at_for(::Comfy::Cms::Page), get_last_updated_at_for(::Comfy::Cms::Snippet)] do
  .segment
    h4 Links
    ul.nolist
      - ::Comfy::Cms::Page.root.children.published.each do |page|
        - if cms_fragment_content(:footer_nav_item, page) == true
          li= link_to page.full_path do
            i.fa(class="fa-#{cms_fragment_content(:nav_item_icon, page).presence || "angle-right"}")
            =< page.label
            - if page.children.size > 0
              ul.nolist
                - page.children.published.each do |child|
                  li= link_to child.full_path do
                    i.fa(class="fa-#{cms_fragment_content(:nav_item_icon, child).presence || "angle-right"}")
                    =< child.label
  .segment
    h4 Intern
    ul.nolist
      - if current_user
        li= link_to main_app.profile_path(current_user) do
          i.fa.fa-user
          =< t('navigation.profile')

        li= link_to destroy_user_session_path, method: :delete do
          i.fa.fa-user
          =<  t('navigation.signed_out')
      - else
        li= link_to new_session_path(User)
          i.fa.fa-sign-in-alt
          =< t('navigation.login')

  = cms_snippet_content('footer', @cms_site).html_safe

.float_right
  .segment
.clear

span.right
  |© 
  => Time.new.year
  span.copyright.bold
    |agil-verWirklichen.de

app/views/shared/_page_header.html.slim
#autohide
  #header_content
    a[href="/"]= image_pack_tag('media/images/logo.svg', alt: Figaro.env.app_header, class: :logo)
    - if !is_mobile_device?
      - cache_if !user_signed_in?, ['page_header_desktop', get_last_updated_at_for(::Comfy::Cms::Snippet)] do
        ul#head_navigation.hover_menu.js-hover_menu.hide_on_tablet_and_mobile
          = cms_snippet_content('main_navbar').html_safe
          - if user_signed_in?
            li.nolist.entry= link_to main_app.profile_path(current_user), rel: :nofollow do
              i.fa.fa-user
          - else
            li.nolist.entry= link_to main_app.new_user_session_path, rel: :nofollow do
              i.fa.fa-user
      
  .clear